# SPDX-FileCopyrightText: 2018 Nate Foster
#
# SPDX-License-Identifier: Apache-2.0
BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = topo_trabalho2.json

include ../../utils/Makefile

test: dirs
	./runptf.sh
